# Generated by Django 4.2.7 on 2024-02-28
from django.db import migrations
from django.contrib.auth.hashers import make_password
import datetime


def create_mock_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Post = apps.get_model('comments', 'Post')
    Comment = apps.get_model('comments', 'Comment')
    PostLike = apps.get_model('comments', 'PostLike')
    CommentLike = apps.get_model('comments', 'CommentLike')

    users = []
    user_data = [
        {'username': 'john_doe', 'email': 'john@example.com', 'first_name': 'John', 'last_name': 'Doe'},
        {'username': 'jane_smith', 'email': 'jane@example.com', 'first_name': 'Jane', 'last_name': 'Smith'},
        {'username': 'bob_wilson', 'email': 'bob@example.com', 'first_name': 'Bob', 'last_name': 'Wilson'},
        {'username': 'alice_brown', 'email': 'alice@example.com', 'first_name': 'Alice', 'last_name': 'Brown'},
    ]

    for data in user_data:
        user = User.objects.create(
            username=data['username'],
            email=data['email'],
            first_name=data['first_name'],
            last_name=data['last_name'],
            password=make_password('password123'),
            is_active=True
        )
        users.append(user)

    posts = []
    post_data = [
        {'title': 'Введение в Django', 'content': 'Django - это высокоуровневый веб-фреймворк на Python...'},
        {'title': 'REST API с DRF', 'content': 'Django REST Framework позволяет быстро создавать API...'},
        {'title': 'Работа с базами данных', 'content': 'Django ORM предоставляет удобный способ работы с БД...'},
        {'title': 'Тестирование в Django', 'content': 'Модуль unittest и pytest для тестирования...'},
    ]

    for i, data in enumerate(post_data):
        post = Post.objects.create(
            title=data['title'],
            content=data['content'],
            author=users[i % len(users)],
            created_at=datetime.datetime.now() - datetime.timedelta(days=i)
        )
        posts.append(post)

    comments = []
    comment_texts = [
        'Отличная статья!',
        'Спасибо за информацию',
        'Очень полезно',
        'А можно подробнее?',
        'У меня тоже такой опыт',
        'Интересная точка зрения',
    ]

    for i, post in enumerate(posts[:2]):
        for j, text in enumerate(comment_texts[:3]):
            comment = Comment.objects.create(
                post=post,
                author=users[j % len(users)],
                content=text,
                created_at=datetime.datetime.now() - datetime.timedelta(hours=j)
            )
            comments.append(comment)

    for i, post in enumerate(posts[:3]):
        for j, user in enumerate(users[:2]):
            PostLike.objects.create(
                post=post,
                user=user,
                created_at=datetime.datetime.now() - datetime.timedelta(days=1)
            )

    for i, comment in enumerate(comments[:4]):
        for j, user in enumerate(users[1:3]):
            CommentLike.objects.create(
                comment=comment,
                user=user,
                created_at=datetime.datetime.now() - datetime.timedelta(hours=i)
            )


def remove_mock_data(apps, schema_editor):
    """Откат миграции - удаляем все мок данные"""
    User = apps.get_model('auth', 'User')
    Post = apps.get_model('comments', 'Post')
    Comment = apps.get_model('comments', 'Comment')
    PostLike = apps.get_model('comments', 'PostLike')
    CommentLike = apps.get_model('comments', 'CommentLike')

    CommentLike.objects.all().delete()
    PostLike.objects.all().delete()
    Comment.objects.all().delete()
    Post.objects.all().delete()
    User.objects.filter(username__in=['john_doe', 'jane_smith', 'bob_wilson', 'alice_brown']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_mock_data, remove_mock_data),
    ]